allow pruning restic before backing up in rbkup

diff --git a/misc-binaries/bin/rbkup b/misc-binaries/bin/rbkup
--- a/misc-binaries/bin/rbkup
+++ b/misc-binaries/bin/rbkup
@@ -46,6 +46,17 @@ if [ -z ${RESTIC_PASSWORD+x} ]; then
 	echo ""
 fi
 
+if [ "$PRUNE_FIRST" = "1" ]; then
+	sep
+	if restic prune; then
+		sep
+		echo -e "${BLU}Pruned!${CLR}"
+	else
+		echo -e "${RED}ACTION REQUIRED: PRUNING FAILED${CLR}"
+		exit 3
+	fi
+fi
+
 if [ "$JUST_CHECK" = "1" ] || restic --one-file-system --verbose backup $HOME --exclude-file="$EXCLUDE_FILE"; then
 	sep
 	echo -e "${BLU}Checking if everything is OK${CLR}"
